// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtrQKqMssUrBBD43sQmkSUx7K6BaUGats',
    appId: '1:331009163526:android:61dd23468d333dd86b5e87',
    messagingSenderId: '331009163526',
    projectId: 'chatapp-70a75',
    storageBucket: 'chatapp-70a75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE0qWnIjM4CJIo7KVeoocrdJPJWBu-ttk',
    appId: '1:331009163526:ios:13bf4951c2b121b66b5e87',
    messagingSenderId: '331009163526',
    projectId: 'chatapp-70a75',
    storageBucket: 'chatapp-70a75.appspot.com',
    androidClientId: '331009163526-f772bdpqdgmmntp62tqfkh46g8fuqb8k.apps.googleusercontent.com',
    iosClientId: '331009163526-b59fc7ei6ckmisopovg4d8v0urqapci7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pookie',
  );

}